version: "3"

volumes:
  db-data:


services:
  api:
    build: api
    ports:
      - "8080:8080"
    depends_on:
      - redis_db
      # - mysql_db
    environment:
      - REDIS_HOST=redis_db:6379
      - REDIS_PORT=6379
      - APP_PORT=:8080
      - APP_HOST=localhost:8080
      - MYSQL_ROOT_PASSWORD=root_pwd
  redis_db:
    build: Database
    ports:
      - "6379:6379"
    volumes:
      - db-data:/data
    image: redis:alpine
  # mysql_db:
  #   image: mysql
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root_pwd

