version: "3"

volumes:
  db-data:


services:
  api:
    build: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - REDIS_HOST=db:6379
      - REDIS_PORT=6379
      - APP_PORT=:8080
      - APP_HOST=localhost:8080
  db:
    build: Database
    ports:
      - "6379:6379"
    volumes:
      - db-data:/data
    image: redis:alpine

